use super::*;

// ── JetBrains tests ───────────────────────────────────────────────────

#[test]
fn jetbrains_generate_basic_target() {
	let runfile = make_runfile(vec![("build", vec!["cargo build"])]);
	let configs = generate_jetbrains_configs(&runfile);
	assert_eq!(configs.len(), 1);
	assert_eq!(configs[0].config_name, "Build");
	assert_eq!(configs[0].target_name, "build");
	assert_eq!(configs[0].file_name, "Runfile_build.run.xml");
	assert!(configs[0].xml.contains("name=\"Build\""));
	assert!(configs[0].xml.contains("value=\"run --stdin-args build\""));
	assert!(configs[0].xml.contains("ShConfigurationType"));
	assert!(configs[0].xml.contains("$PROJECT_DIR$"));
}

#[test]
fn jetbrains_execute_in_terminal_is_false() {
	let runfile = make_runfile(vec![("build", vec!["cargo build"])]);
	let configs = generate_jetbrains_configs(&runfile);
	assert!(configs[0].xml.contains("name=\"EXECUTE_IN_TERMINAL\" value=\"false\""));
}

#[test]
fn jetbrains_colon_in_target_name_becomes_capitalized_words() {
	let runfile = make_runfile(vec![("build:infrastructure", vec!["cargo build"])]);
	let configs = generate_jetbrains_configs(&runfile);
	assert_eq!(configs[0].config_name, "Build Infrastructure");
	assert_eq!(configs[0].target_name, "build:infrastructure");
	assert_eq!(configs[0].file_name, "Runfile_build_infrastructure.run.xml");
	assert!(configs[0].xml.contains("name=\"Build Infrastructure\""));
	// SCRIPT_TEXT keeps the original target name so `run` resolves it correctly.
	assert!(configs[0]
		.xml
		.contains("value=\"run --stdin-args build:infrastructure\""));
}

#[test]
fn jetbrains_punctuation_variants_become_whitespace() {
	let runfile = make_runfile(vec![
		("test.unit.fast", vec!["cargo test"]),
		("ci/build", vec!["cargo build"]),
		("deploy,prod", vec!["deploy"]),
		("build_release", vec!["cargo build --release"]),
	]);
	let configs = generate_jetbrains_configs(&runfile);
	let names: Vec<&str> = configs.iter().map(|c| c.config_name.as_str()).collect();
	// Sorted alphabetically by target name: "build_release", "ci/build", "deploy,prod", "test.unit.fast"
	assert_eq!(
		names,
		vec!["Build Release", "Ci Build", "Deploy Prod", "Test Unit Fast"]
	);
}

#[test]
fn jetbrains_targets_sorted_alphabetically() {
	let runfile = make_runfile(vec![("test", vec!["cargo test"]), ("build", vec!["cargo build"])]);
	let configs = generate_jetbrains_configs(&runfile);
	assert_eq!(configs[0].config_name, "Build");
	assert_eq!(configs[1].config_name, "Test");
}

#[test]
fn jetbrains_check_ours_current_format() {
	let xml = r#"<configuration default="false" name="Build" type="ShConfigurationType">
    <option name="SCRIPT_TEXT" value="run --stdin-args build" />"#;
	assert!(matches!(
		check_existing_jetbrains_config(xml, "Build", "build"),
		JetBrainsConfigCheck::Ours
	));
}

#[test]
fn jetbrains_check_ours_pre_stdin_args_format() {
	// Files generated before the `--stdin-args` switch still have the bare
	// `run <target>` form. Treat them as ours so re-running the generator
	// upgrades them in place.
	let xml = r#"<configuration default="false" name="Build" type="ShConfigurationType">
    <option name="SCRIPT_TEXT" value="run build" />"#;
	assert!(matches!(
		check_existing_jetbrains_config(xml, "Build", "build"),
		JetBrainsConfigCheck::Ours
	));
}

#[test]
fn jetbrains_check_recognizes_legacy_format() {
	// Files generated by even older versions still carry the "Runfile / <target>" prefix; treat them as ours
	// so re-running the generator overwrites them in place rather than skipping them as foreign.
	let xml = r#"<configuration default="false" name="Runfile / build" type="ShConfigurationType">
    <option name="SCRIPT_TEXT" value="run build" />"#;
	assert!(matches!(
		check_existing_jetbrains_config(xml, "Build", "build"),
		JetBrainsConfigCheck::Ours
	));
}

#[test]
fn jetbrains_check_foreign_name() {
	let xml = r#"<configuration default="false" name="My Custom Build" type="ShConfigurationType">
    <option name="SCRIPT_TEXT" value="run --stdin-args build" />"#;
	assert!(matches!(
		check_existing_jetbrains_config(xml, "Build", "build"),
		JetBrainsConfigCheck::Foreign(_)
	));
}

#[test]
fn jetbrains_check_foreign_script() {
	let xml = r#"<configuration default="false" name="Build" type="ShConfigurationType">
    <option name="SCRIPT_TEXT" value="make build" />"#;
	assert!(matches!(
		check_existing_jetbrains_config(xml, "Build", "build"),
		JetBrainsConfigCheck::Foreign(_)
	));
}

#[test]
fn jetbrains_is_ours_recognises_current_format() {
	let runfile = make_runfile(vec![("build", vec!["cargo build"])]);
	let xml = &generate_jetbrains_configs(&runfile)[0].xml;
	assert!(is_jetbrains_config_ours(xml));
}

#[test]
fn jetbrains_is_ours_recognises_legacy_run_form() {
	// Pre-`--stdin-args` files only had `value="run <target>"`.
	let xml = r#"<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Build" type="ShConfigurationType">
    <option name="SCRIPT_TEXT" value="run build" />
    <option name="SCRIPT_WORKING_DIRECTORY" value="$PROJECT_DIR$" />
  </configuration>
</component>"#;
	assert!(is_jetbrains_config_ours(xml));
}

#[test]
fn jetbrains_is_ours_rejects_foreign_type() {
	// Right command in script, wrong configuration type — likely a hand-written config.
	let xml = r#"<configuration default="false" name="Build" type="MavenRunConfiguration">
    <option name="SCRIPT_TEXT" value="run build" />
    <option name="SCRIPT_WORKING_DIRECTORY" value="$PROJECT_DIR$" />
</configuration>"#;
	assert!(!is_jetbrains_config_ours(xml));
}

#[test]
fn jetbrains_is_ours_rejects_foreign_script() {
	// Shell config but not invoking `run`.
	let xml = r#"<configuration default="false" name="Build" type="ShConfigurationType">
    <option name="SCRIPT_TEXT" value="make build" />
    <option name="SCRIPT_WORKING_DIRECTORY" value="$PROJECT_DIR$" />
</configuration>"#;
	assert!(!is_jetbrains_config_ours(xml));
}

#[test]
fn jetbrains_is_ours_rejects_missing_working_directory_marker() {
	// Shell config + run script, but without our distinctive `$PROJECT_DIR$` marker —
	// a hand-authored config that happens to invoke `run`.
	let xml = r#"<configuration default="false" name="Build" type="ShConfigurationType">
    <option name="SCRIPT_TEXT" value="run build" />
</configuration>"#;
	assert!(!is_jetbrains_config_ours(xml));
}

#[test]
fn jetbrains_xml_is_valid_structure() {
	let runfile = make_runfile(vec![("test", vec!["cargo test"])]);
	let configs = generate_jetbrains_configs(&runfile);
	let xml = &configs[0].xml;
	assert!(xml.starts_with("<component"));
	assert!(xml.trim_end().ends_with("</component>"));
	assert!(xml.contains("<method v=\"2\" />"));
	assert!(xml.contains("<envs />"));
	assert!(xml.contains("EXECUTE_IN_TERMINAL"));
}
