use runfile_parser::{is_internal_target_name, Runfile};

/// A generated JetBrains run configuration.
pub struct JetBrainsRunConfig {
	/// Display name, e.g. "Build Infrastructure" (from target "build:infrastructure").
	pub config_name: String,
	/// Original target name as written in Runfile.json (used for the `run <target>` script and overwrite checks).
	pub target_name: String,
	/// Safe file name, e.g. "Runfile_build_infrastructure.run.xml".
	pub file_name: String,
	/// Full XML content for the .run.xml file.
	pub xml: String,
}

/// Result of checking an existing run configuration file.
pub enum JetBrainsConfigCheck {
	/// The file was generated by us — safe to overwrite.
	Ours,
	/// The file has a different configuration — do not overwrite.
	Foreign(String),
}

/// Generate JetBrains run configurations for all targets in a Runfile.
///
/// Targets are skipped when their (possibly-globals-merged) metadata sets
/// `excludeFromGenerateCommand: true`, alongside the existing rule that
/// hides internal `_`-prefixed targets.
pub fn generate_jetbrains_configs(runfile: &Runfile) -> Vec<JetBrainsRunConfig> {
	let mut target_names: Vec<&String> = runfile
		.targets
		.iter()
		.filter(|(n, spec)| !is_internal_target_name(n) && !spec.is_excluded_from_generate())
		.map(|(n, _)| n)
		.collect();
	target_names.sort();

	target_names
		.iter()
		.map(|name| {
			let config_name = prettify_target_name(name);
			let file_name = format!("Runfile_{}.run.xml", sanitize_file_name(name));
			let xml = build_jetbrains_run_config(&config_name, name);
			JetBrainsRunConfig {
				config_name,
				target_name: (*name).clone(),
				file_name,
				xml,
			}
		})
		.collect()
}

/// Check whether an existing file was generated by us and is safe to overwrite.
///
/// Recognizes both the current naming format and the legacy `Runfile / <target>` format
/// so older generated files can be migrated in place. Also accepts both the current
/// script text (`run --stdin-args <target>`) and the legacy form (`run <target>`) so
/// configs generated before the `--stdin-args` switch are upgraded in place.
pub fn check_existing_jetbrains_config(contents: &str, expected_name: &str, target_name: &str) -> JetBrainsConfigCheck {
	let new_name_attr = format!("name=\"{expected_name}\"");
	let legacy_name_attr = format!("name=\"Runfile / {target_name}\"");
	if !contents.contains(&new_name_attr) && !contents.contains(&legacy_name_attr) {
		return JetBrainsConfigCheck::Foreign(format!("configuration name does not match \"{expected_name}\""));
	}

	let current_script = format!("name=\"SCRIPT_TEXT\" value=\"run --stdin-args {target_name}\"");
	let legacy_script = format!("name=\"SCRIPT_TEXT\" value=\"run {target_name}\"");
	if !contents.contains(&current_script) && !contents.contains(&legacy_script) {
		return JetBrainsConfigCheck::Foreign(format!("script text does not match \"run --stdin-args {target_name}\""));
	}

	JetBrainsConfigCheck::Ours
}

/// Convert a target name into a human-friendly run configuration title.
///
/// Non-alphanumeric characters become whitespace boundaries, then each resulting word is capitalized.
/// `"build:infrastructure"` → `"Build Infrastructure"`, `"test.unit.fast"` → `"Test Unit Fast"`.
fn prettify_target_name(name: &str) -> String {
	name.chars()
		.map(|c| if c.is_alphanumeric() { c } else { ' ' })
		.collect::<String>()
		.split_whitespace()
		.map(capitalize_word)
		.collect::<Vec<_>>()
		.join(" ")
}

fn capitalize_word(word: &str) -> String {
	let mut chars = word.chars();
	match chars.next() {
		Some(first) => first.to_uppercase().chain(chars).collect(),
		None => String::new(),
	}
}

/// Replace any non-alphanumeric character with `_` so the result is safe as a filename component.
fn sanitize_file_name(name: &str) -> String {
	name.chars()
		.map(|c| if c.is_alphanumeric() { c } else { '_' })
		.collect()
}

fn build_jetbrains_run_config(config_name: &str, target_name: &str) -> String {
	// `--stdin-args` makes Runfile prompt for any unsupplied {{ ARGS.x }} /
	// {{ ENV.X }} / {{ FLAGS.x }} value via stdin. Run configurations are static
	// (no per-invocation parameter UI), so without the flag a target with a
	// required arg would just fail. The flag is a no-op when nothing's
	// missing, so it's safe to always include.
	format!(
		r#"<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="{config_name}" type="ShConfigurationType">
    <option name="SCRIPT_TEXT" value="run --stdin-args {target_name}" />
    <option name="INDEPENDENT_SCRIPT_PATH" value="true" />
    <option name="SCRIPT_PATH" value="" />
    <option name="SCRIPT_OPTIONS" value="" />
    <option name="INDEPENDENT_SCRIPT_WORKING_DIRECTORY" value="true" />
    <option name="SCRIPT_WORKING_DIRECTORY" value="$PROJECT_DIR$" />
    <option name="INDEPENDENT_INTERPRETER_PATH" value="true" />
    <option name="INTERPRETER_PATH" value="" />
    <option name="INTERPRETER_OPTIONS" value="" />
    <option name="EXECUTE_IN_TERMINAL" value="false" />
    <option name="EXECUTE_SCRIPT_FILE" value="false" />
    <envs />
    <method v="2" />
  </configuration>
</component>
"#
	)
}
