use crate::editorconfig::EditorConfigProps;
use runfile_parser::{Runfile, is_internal_target_name};

/// A generated JetBrains run configuration.
pub struct JetBrainsRunConfig {
	/// Display name, e.g. "Build Infrastructure" (from target "build:infrastructure").
	pub config_name: String,
	/// Original target name as written in Runfile.json (used for the `run <target>` script and overwrite checks).
	pub target_name: String,
	/// Safe file name, e.g. "Runfile_build_infrastructure.run.xml".
	pub file_name: String,
	/// Full XML content for the .run.xml file.
	pub xml: String,
}

/// Result of checking an existing run configuration file.
pub enum JetBrainsConfigCheck {
	/// The file was generated by us — safe to overwrite.
	Ours,
	/// The file has a different configuration — do not overwrite.
	Foreign(String),
}

/// Generate JetBrains run configurations for all targets in a Runfile.
///
/// Targets are skipped when their (possibly-globals-merged) metadata sets
/// `excludeFromGenerateCommand: true`, alongside the existing rule that
/// hides internal `_`-prefixed targets.
pub fn generate_jetbrains_configs(runfile: &Runfile) -> Vec<JetBrainsRunConfig> {
	let mut target_names: Vec<&String> = runfile
		.targets
		.iter()
		.filter(|(n, spec)| !is_internal_target_name(n) && !spec.is_excluded_from_generate())
		.map(|(n, _)| n)
		.collect();
	target_names.sort();

	target_names
		.iter()
		.map(|name| {
			let config_name = prettify_target_name(name);
			let file_name = format!("Runfile_{}.run.xml", sanitize_file_name(name));
			let xml = build_jetbrains_run_config(&config_name, name, None);
			JetBrainsRunConfig {
				config_name,
				target_name: (*name).clone(),
				file_name,
				xml,
			}
		})
		.collect()
}

/// Check whether an existing file was generated by us and is safe to overwrite.
///
/// Recognizes both the current naming format and the legacy `Runfile / <target>` format
/// so older generated files can be migrated in place. Also accepts both the current
/// script text (`run --stdin-args <target>`) and the legacy form (`run <target>`) so
/// configs generated before the `--stdin-args` switch are upgraded in place.
pub fn check_existing_jetbrains_config(contents: &str, expected_name: &str, target_name: &str) -> JetBrainsConfigCheck {
	let new_name_attr = format!("name=\"{expected_name}\"");
	let legacy_name_attr = format!("name=\"Runfile / {target_name}\"");
	if !contents.contains(&new_name_attr) && !contents.contains(&legacy_name_attr) {
		return JetBrainsConfigCheck::Foreign(format!("configuration name does not match \"{expected_name}\""));
	}

	let current_script = format!("name=\"SCRIPT_TEXT\" value=\"run --stdin-args {target_name}\"");
	let legacy_script = format!("name=\"SCRIPT_TEXT\" value=\"run {target_name}\"");
	if !contents.contains(&current_script) && !contents.contains(&legacy_script) {
		return JetBrainsConfigCheck::Foreign(format!("script text does not match \"run --stdin-args {target_name}\""));
	}

	JetBrainsConfigCheck::Ours
}

/// Decide whether an arbitrary `.run.xml` file in the run-configs directory was generated
/// by us, without needing to know which target it was generated for.
///
/// Used by `:generate jetbrains-run-configurations` to prune stale files (targets that no
/// longer exist in the Runfile) without touching user-authored configurations. Anchored on
/// three structural markers our generator always emits together: a `ShConfigurationType`
/// configuration, a `SCRIPT_TEXT` that runs the `run` binary (covers both the current
/// `run --stdin-args <target>` and the legacy `run <target>` forms — the leading
/// `value="run ` prefix is shared), and our distinctive `SCRIPT_WORKING_DIRECTORY` value.
/// User-written XML in `.run/` would have to coincidentally hit all three to be flagged.
pub fn is_jetbrains_config_ours(contents: &str) -> bool {
	contents.contains("type=\"ShConfigurationType\"")
		&& contents.contains("name=\"SCRIPT_TEXT\" value=\"run ")
		&& contents.contains("name=\"SCRIPT_WORKING_DIRECTORY\" value=\"$PROJECT_DIR$\"")
}

/// Convert a target name into a human-friendly run configuration title.
///
/// Non-alphanumeric characters become whitespace boundaries, then each resulting word is capitalized.
/// `"build:infrastructure"` → `"Build Infrastructure"`, `"test.unit.fast"` → `"Test Unit Fast"`.
fn prettify_target_name(name: &str) -> String {
	name.chars()
		.map(|c| if c.is_alphanumeric() { c } else { ' ' })
		.collect::<String>()
		.split_whitespace()
		.map(capitalize_word)
		.collect::<Vec<_>>()
		.join(" ")
}

fn capitalize_word(word: &str) -> String {
	let mut chars = word.chars();
	match chars.next() {
		Some(first) => first.to_uppercase().chain(chars).collect(),
		None => String::new(),
	}
}

/// Replace any non-alphanumeric character with `_` so the result is safe as a filename component.
fn sanitize_file_name(name: &str) -> String {
	name.chars()
		.map(|c| if c.is_alphanumeric() { c } else { '_' })
		.collect()
}

/// Render a JetBrains run configuration to the exact bytes to write to `.run/<name>.run.xml`,
/// formatted per the resolved EditorConfig properties: the indentation unit drives the XML
/// structure and the remaining settings (line endings, trailing whitespace, final newline, BOM)
/// are applied to the text. With an empty [`EditorConfigProps`] this reproduces the previous
/// output (2-space indent, LF, trailing newline).
pub fn render_jetbrains_config(config_name: &str, target_name: &str, props: &EditorConfigProps) -> Vec<u8> {
	let indent = props.indent_unit();
	let xml = build_jetbrains_run_config(config_name, target_name, indent.as_deref());
	props.apply(&xml)
}

/// Escape a string for safe inclusion in a double-quoted XML attribute value.
/// Target names are only forbidden from starting with `:`, containing `?`, or
/// being empty, so `"`, `<`, `>`, `&` are all valid in a name — and a name
/// carrying a `"` would otherwise break out of the `value="…"` attribute and
/// inject arbitrary `<option>` / `<configuration>` XML (attacker-controlled
/// `SCRIPT_TEXT` that the IDE would execute). Reachable via `:convert` of an
/// untrusted Makefile / package.json.
fn xml_escape_attr(s: &str) -> String {
	let mut out = String::with_capacity(s.len());
	for c in s.chars() {
		match c {
			'&' => out.push_str("&amp;"),
			'<' => out.push_str("&lt;"),
			'>' => out.push_str("&gt;"),
			'"' => out.push_str("&quot;"),
			'\'' => out.push_str("&apos;"),
			_ => out.push(c),
		}
	}
	out
}

fn build_jetbrains_run_config(config_name: &str, target_name: &str, indent: Option<&str>) -> String {
	let config_name = xml_escape_attr(config_name);
	let target_name = xml_escape_attr(target_name);
	// `--stdin-args` makes Runfile prompt for any unsupplied {{ ARG.x }} /
	// {{ ENV.X }} / {{ FLAG.x }} value via stdin. Run configurations are static
	// (no per-invocation parameter UI), so without the flag a target with a
	// required arg would just fail. The flag is a no-op when nothing's
	// missing, so it's safe to always include.
	//
	// `i1` is one indentation level (the `<configuration>` element), `i2` is two (its
	// `<option>` children); both default to two spaces to match historical output.
	let i1 = indent.unwrap_or("  ");
	let i2 = format!("{i1}{i1}");
	format!(
		r#"<component name="ProjectRunConfigurationManager">
{i1}<configuration default="false" name="{config_name}" type="ShConfigurationType">
{i2}<option name="SCRIPT_TEXT" value="run --stdin-args {target_name}" />
{i2}<option name="INDEPENDENT_SCRIPT_PATH" value="true" />
{i2}<option name="SCRIPT_PATH" value="" />
{i2}<option name="SCRIPT_OPTIONS" value="" />
{i2}<option name="INDEPENDENT_SCRIPT_WORKING_DIRECTORY" value="true" />
{i2}<option name="SCRIPT_WORKING_DIRECTORY" value="$PROJECT_DIR$" />
{i2}<option name="INDEPENDENT_INTERPRETER_PATH" value="true" />
{i2}<option name="INTERPRETER_PATH" value="" />
{i2}<option name="INTERPRETER_OPTIONS" value="" />
{i2}<option name="EXECUTE_IN_TERMINAL" value="false" />
{i2}<option name="EXECUTE_SCRIPT_FILE" value="false" />
{i2}<envs />
{i2}<method v="2" />
{i1}</configuration>
</component>
"#
	)
}
