name: CI

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@v1.16.1
      - uses: ./.github/actions/setup
        with:
          from-source: true
          global-files: Runfile-ci.json
      - run: run ci:lint

  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@v1.16.1
      - uses: ./.github/actions/setup
        with:
          from-source: true
          global-files: Runfile-ci.json
      - run: run ci:test
